# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RequestTest1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RequestTest1
    pod 'Alamofire'
    pod 'SDWebImage'
  target 'RequestTest1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RequestTest1UITests' do
    # Pods for testing
  end

end
